/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class AutoCommandActionResult : ActionResult<AutoCommandResult>
    {
        public const string RosMessageName = "astra_msgs/action/AutoCommandActionResult";

        public AutoCommandActionResult() : base()
        {
            this.values = new AutoCommandResult();
        }

        public AutoCommandActionResult(Header header, string action, sbyte status, bool result, string id, AutoCommandResult values) : base(header, action, status, result, id)
        {
            this.values = values;
        }
    }
}
