/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class AutoCommandGoal : Message
    {
        public const string RosMessageName = "astra_msgs/action/AutoCommandGoal";

        //  Goal
        public long mission_type { get; set; }
        public double gps_lat_target { get; set; }
        public double gps_long_target { get; set; }
        public double target_radius { get; set; }
        public double period { get; set; }

        public AutoCommandGoal()
        {
            this.mission_type = 0;
            this.gps_lat_target = 0.0;
            this.gps_long_target = 0.0;
            this.target_radius = 0.0;
            this.period = 0.0;
        }

        public AutoCommandGoal(long mission_type, double gps_lat_target, double gps_long_target, double target_radius, double period)
        {
            this.mission_type = mission_type;
            this.gps_lat_target = gps_lat_target;
            this.gps_long_target = gps_long_target;
            this.target_radius = target_radius;
            this.period = period;
        }
    }
}
