/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class AutoCommandAction : Action<AutoCommandActionGoal, AutoCommandActionResult, AutoCommandActionFeedback, AutoCommandGoal, AutoCommandResult, AutoCommandFeedback>
    {
        public const string RosMessageName = "astra_msgs/action/AutoCommandAction";

        public AutoCommandAction() : base()
        {
            this.action_goal = new AutoCommandActionGoal();
            this.action_result = new AutoCommandActionResult();
            this.action_feedback = new AutoCommandActionFeedback();
        }

    }
}
