/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class AutoCommandFeedback : Message
    {
        public const string RosMessageName = "astra_msgs/action/AutoCommandFeedback";

        //  Feeedback
        public long current_status { get; set; }
        public double distance_remaining { get; set; }

        public AutoCommandFeedback()
        {
            this.current_status = 0;
            this.distance_remaining = 0.0;
        }

        public AutoCommandFeedback(long current_status, double distance_remaining)
        {
            this.current_status = current_status;
            this.distance_remaining = distance_remaining;
        }
    }
}
