/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class AutoCommandResult : Message
    {
        public const string RosMessageName = "astra_msgs/action/AutoCommandResult";

        //  Result
        public long final_result { get; set; }

        public AutoCommandResult()
        {
            this.final_result = 0;
        }

        public AutoCommandResult(long final_result)
        {
            this.final_result = final_result;
        }
    }
}
