/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Action;

namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class BioVacuumActionGoal : ActionGoal<BioVacuumGoal>
    {
        public const string RosMessageName = "astra_msgs/action/BioVacuumActionGoal";

        public BioVacuumActionGoal() : base()
        {
            this.args = new BioVacuumGoal();
        }

        public BioVacuumActionGoal(Header header, GoalInfo goalInfo, BioVacuumGoal args) : base(header, goalInfo)
        {
            this.args = args;
        }
    }
}
