/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class BioVacuumActionFeedback : ActionFeedback<BioVacuumFeedback>
    {
        public const string RosMessageName = "astra_msgs/action/BioVacuumActionFeedback";

        public BioVacuumActionFeedback() : base()
        {
            this.values = new BioVacuumFeedback();
        }

        public BioVacuumActionFeedback(Header header, string id, string action, BioVacuumFeedback values) : base(header, id, action)
        {
            this.values = values;
        }
    }
}
