/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class BioVacuumResult : Message
    {
        public const string RosMessageName = "astra_msgs/action/BioVacuumResult";

        //  Feedback
        public bool requested_valve_open { get; set; }
        public sbyte requested_fan_duty_cycle { get; set; }

        public BioVacuumResult()
        {
            this.requested_valve_open = false;
            this.requested_fan_duty_cycle = 0;
        }

        public BioVacuumResult(bool requested_valve_open, sbyte requested_fan_duty_cycle)
        {
            this.requested_valve_open = requested_valve_open;
            this.requested_fan_duty_cycle = requested_fan_duty_cycle;
        }
    }
}
