/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class BioVacuumGoal : Message
    {
        public const string RosMessageName = "astra_msgs/action/BioVacuumGoal";

        //  Goal
        public sbyte valve_id { get; set; }
        // (0-2)
        public sbyte fan_duty_cycle_percent { get; set; }
        // (0-100)
        public uint fan_time_ms { get; set; }

        public BioVacuumGoal()
        {
            this.valve_id = 0;
            this.fan_duty_cycle_percent = 0;
            this.fan_time_ms = 0;
        }

        public BioVacuumGoal(sbyte valve_id, sbyte fan_duty_cycle_percent, uint fan_time_ms)
        {
            this.valve_id = valve_id;
            this.fan_duty_cycle_percent = fan_duty_cycle_percent;
            this.fan_time_ms = fan_time_ms;
        }
    }
}
