/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class BioVacuumResult : Message
    {
        public const string RosMessageName = "astra_msgs/action/BioVacuumResult";

        //  Feedback
        public uint fan_time_remaining_ms { get; set; }

        public BioVacuumResult()
        {
            this.fan_time_remaining_ms = 0;
        }

        public BioVacuumResult(uint fan_time_remaining_ms)
        {
            this.fan_time_remaining_ms = fan_time_remaining_ms;
        }
    }
}
