/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class BioVacuumFeedback : Message
    {
        public const string RosMessageName = "astra_msgs/action/BioVacuumFeedback";

        //  Feedback
        public uint fan_time_remaining_ms { get; set; }
        //  Request the valve to open and the duty cycle and duration to run the fan for.
        //  process: open valve n, wait (x)ms, run fan for y, close valve n, wait (x)ms, result

        public BioVacuumFeedback()
        {
            this.fan_time_remaining_ms = 0;
        }

        public BioVacuumFeedback(uint fan_time_remaining_ms)
        {
            this.fan_time_remaining_ms = fan_time_remaining_ms;
        }
    }
}
