# Goal
byte valve_id # (0-2)
byte fan_duty_cycle_percent # (0-100) 
uint32 fan_time_ms 
---
# Result
# Nothing.
---
# Feedback
uint32 fan_time_remaining_ms

# Request the valve to open and the duty cycle and duration to run the fan for.
# process: open valve n, wait (x)ms, run fan for y, close valve n, wait (x)ms, result
