/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class QueryTrajectoryStateRequest : Message
    {
        public const string RosMessageName = "control_msgs/srv/QueryTrajectoryState";

        public Time time { get; set; }

        public QueryTrajectoryStateRequest()
        {
            this.time = new Time();
        }

        public QueryTrajectoryStateRequest(Time time)
        {
            this.time = time;
        }
    }
}
