/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class QueryTrajectoryStateResponse : Message
    {
        public const string RosMessageName = "control_msgs/srv/QueryTrajectoryState";

        public bool success { get; set; }
        // indicate successful run of triggered service
        public string message { get; set; }
        // informational, e.g. for error messages
        public string[] name { get; set; }
        public double[] position { get; set; }
        public double[] velocity { get; set; }
        public double[] acceleration { get; set; }

        public QueryTrajectoryStateResponse()
        {
            this.success = false;
            this.message = "";
            this.name = new string[0];
            this.position = new double[0];
            this.velocity = new double[0];
            this.acceleration = new double[0];
        }

        public QueryTrajectoryStateResponse(bool success, string message, string[] name, double[] position, double[] velocity, double[] acceleration)
        {
            this.success = success;
            this.message = message;
            this.name = name;
            this.position = position;
            this.velocity = velocity;
            this.acceleration = acceleration;
        }
    }
}
