/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class QueryCalibrationStateResponse : Message
    {
        public const string RosMessageName = "control_msgs/srv/QueryCalibrationState";

        public bool is_calibrated { get; set; }

        public QueryCalibrationStateResponse()
        {
            this.is_calibrated = false;
        }

        public QueryCalibrationStateResponse(bool is_calibrated)
        {
            this.is_calibrated = is_calibrated;
        }
    }
}
