/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class FollowJointTrajectoryActionResult : ActionResult<FollowJointTrajectoryResult>
    {
        public const string RosMessageName = "control_msgs/action/FollowJointTrajectoryActionResult";

        public FollowJointTrajectoryActionResult() : base()
        {
            this.values = new FollowJointTrajectoryResult();
        }

        public FollowJointTrajectoryActionResult(Header header, string action, sbyte status, bool result, string id, FollowJointTrajectoryResult values) : base(header, action, status, result, id)
        {
            this.values = values;
        }
    }
}
