/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class GripperCommandAction : Action<GripperCommandActionGoal, GripperCommandActionResult, GripperCommandActionFeedback, GripperCommandGoal, GripperCommandResult, GripperCommandFeedback>
    {
        public const string RosMessageName = "control_msgs/action/GripperCommandAction";

        public GripperCommandAction() : base()
        {
            this.action_goal = new GripperCommandActionGoal();
            this.action_result = new GripperCommandActionResult();
            this.action_feedback = new GripperCommandActionFeedback();
        }

    }
}
