/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class JointTrajectoryActionFeedback : ActionFeedback<JointTrajectoryFeedback>
    {
        public const string RosMessageName = "control_msgs/action/JointTrajectoryActionFeedback";

        public JointTrajectoryActionFeedback() : base()
        {
            this.values = new JointTrajectoryFeedback();
        }

        public JointTrajectoryActionFeedback(Header header, string id, string action, JointTrajectoryFeedback values) : base(header, id, action)
        {
            this.values = values;
        }
    }
}
