/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Action;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class JointTrajectoryActionGoal : ActionGoal<JointTrajectoryGoal>
    {
        public const string RosMessageName = "control_msgs/action/JointTrajectoryActionGoal";

        public JointTrajectoryActionGoal() : base()
        {
            this.args = new JointTrajectoryGoal();
        }

        public JointTrajectoryActionGoal(Header header, GoalInfo goalInfo, JointTrajectoryGoal args) : base(header, goalInfo)
        {
            this.args = args;
        }
    }
}
