/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class ParallelGripperCommandAction : Action<ParallelGripperCommandActionGoal, ParallelGripperCommandActionResult, ParallelGripperCommandActionFeedback, ParallelGripperCommandGoal, ParallelGripperCommandResult, ParallelGripperCommandFeedback>
    {
        public const string RosMessageName = "control_msgs/action/ParallelGripperCommandAction";

        public ParallelGripperCommandAction() : base()
        {
            this.action_goal = new ParallelGripperCommandActionGoal();
            this.action_result = new ParallelGripperCommandActionResult();
            this.action_feedback = new ParallelGripperCommandActionFeedback();
        }

    }
}
