/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Sensor;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class ParallelGripperCommandGoal : Message
    {
        public const string RosMessageName = "control_msgs/action/ParallelGripperCommandGoal";

        //  Parallel grippers refer to an end effector where two opposing fingers grasp an object from opposite sides.
        public JointState command { get; set; }
        //  name: the name(s) of the joint this command is requesting
        //  position: desired position of each gripper joint (radians or meters)
        //  velocity: (optional, not used if empty) max velocity of the joint allowed while moving (radians or meters / second)
        //  effort: (optional, not used if empty) max effort of the joint allowed while moving (Newtons or Newton-meters)

        public ParallelGripperCommandGoal()
        {
            this.command = new JointState();
        }

        public ParallelGripperCommandGoal(JointState command)
        {
            this.command = command;
        }
    }
}
