/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Sensor;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class ParallelGripperCommandResult : Message
    {
        public const string RosMessageName = "control_msgs/action/ParallelGripperCommandResult";

        public JointState state { get; set; }
        // The current gripper state.
        //  position of each joint (radians or meters)
        //  optional: velocity of each joint (radians or meters / second)
        //  optional: effort of each joint (Newtons or Newton-meters)
        public bool stalled { get; set; }
        // True if the gripper is exerting max effort and not moving
        public bool reached_goal { get; set; }
        // True if the gripper position has reached the commanded setpoint

        public ParallelGripperCommandResult()
        {
            this.state = new JointState();
            this.stalled = false;
            this.reached_goal = false;
        }

        public ParallelGripperCommandResult(JointState state, bool stalled, bool reached_goal)
        {
            this.state = state;
            this.stalled = stalled;
            this.reached_goal = reached_goal;
        }
    }
}
