/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Sensor;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class ParallelGripperCommandFeedback : Message
    {
        public const string RosMessageName = "control_msgs/action/ParallelGripperCommandFeedback";

        public JointState state { get; set; }
        // The current gripper state.
        //  position of each joint (radians or meters)
        //  optional: velocity of each joint (radians or meters / second)
        //  optional: effort of each joint (Newtons or Newton-meters)

        public ParallelGripperCommandFeedback()
        {
            this.state = new JointState();
        }

        public ParallelGripperCommandFeedback(JointState state)
        {
            this.state = state;
        }
    }
}
