/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class PointHeadAction : Action<PointHeadActionGoal, PointHeadActionResult, PointHeadActionFeedback, PointHeadGoal, PointHeadResult, PointHeadFeedback>
    {
        public const string RosMessageName = "control_msgs/action/PointHeadAction";

        public PointHeadAction() : base()
        {
            this.action_goal = new PointHeadActionGoal();
            this.action_result = new PointHeadActionResult();
            this.action_feedback = new PointHeadActionFeedback();
        }

    }
}
