/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class PointHeadActionResult : ActionResult<PointHeadResult>
    {
        public const string RosMessageName = "control_msgs/action/PointHeadActionResult";

        public PointHeadActionResult() : base()
        {
            this.values = new PointHeadResult();
        }

        public PointHeadActionResult(Header header, string action, sbyte status, bool result, string id, PointHeadResult values) : base(header, action, status, result, id)
        {
            this.values = values;
        }
    }
}
