/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class SingleJointPositionAction : Action<SingleJointPositionActionGoal, SingleJointPositionActionResult, SingleJointPositionActionFeedback, SingleJointPositionGoal, SingleJointPositionResult, SingleJointPositionFeedback>
    {
        public const string RosMessageName = "control_msgs/action/SingleJointPositionAction";

        public SingleJointPositionAction() : base()
        {
            this.action_goal = new SingleJointPositionActionGoal();
            this.action_result = new SingleJointPositionActionResult();
            this.action_feedback = new SingleJointPositionActionFeedback();
        }

    }
}
