/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using RosSharp.RosBridgeClient.MessageTypes.Std;
namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class SingleJointPositionActionFeedback : ActionFeedback<SingleJointPositionFeedback>
    {
        public const string RosMessageName = "control_msgs/action/SingleJointPositionActionFeedback";

        public SingleJointPositionActionFeedback() : base()
        {
            this.values = new SingleJointPositionFeedback();
        }

        public SingleJointPositionActionFeedback(Header header, string id, string action, SingleJointPositionFeedback values) : base(header, id, action)
        {
            this.values = values;
        }
    }
}
