/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class ArmCtrlState : Message
    {
        public const string RosMessageName = "astra_msgs/msg/ArmCtrlState";

        //  /core/control/state
        public bool brake_mode { get; set; }
        // True = brake, False = coast
        public bool laser { get; set; }

        public ArmCtrlState()
        {
            this.brake_mode = false;
            this.laser = false;
        }

        public ArmCtrlState(bool brake_mode, bool laser)
        {
            this.brake_mode = brake_mode;
            this.laser = laser;
        }
    }
}
