/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Astra;

namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class ArmFeedback : Message
    {
        public const string RosMessageName = "astra_msgs/msg/ArmFeedback";

        //  Topic: /arm/new_feedback
        public Header header { get; set; }
        //  Arm REV Motors (axis 0-3)
        public RevMotorState axis0_motor { get; set; }
        public RevMotorState axis1_motor { get; set; }
        public RevMotorState axis2_motor { get; set; }
        public RevMotorState axis3_motor { get; set; }
        //  Socket and Digit PCB voltages
        public BoardVoltage socket_voltage { get; set; }
        public BoardVoltage digit_voltage { get; set; }

        public ArmFeedback()
        {
            this.header = new Header();
            this.axis0_motor = new RevMotorState();
            this.axis1_motor = new RevMotorState();
            this.axis2_motor = new RevMotorState();
            this.axis3_motor = new RevMotorState();
            this.socket_voltage = new BoardVoltage();
            this.digit_voltage = new BoardVoltage();
        }

        public ArmFeedback(Header header, RevMotorState axis0_motor, RevMotorState axis1_motor, RevMotorState axis2_motor, RevMotorState axis3_motor, BoardVoltage socket_voltage, BoardVoltage digit_voltage)
        {
            this.header = header;
            this.axis0_motor = axis0_motor;
            this.axis1_motor = axis1_motor;
            this.axis2_motor = axis2_motor;
            this.axis3_motor = axis3_motor;
            this.socket_voltage = socket_voltage;
            this.digit_voltage = digit_voltage;
        }
    }
}
