/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class ArmIK : Message
    {
        public const string RosMessageName = "astra_msgs/msg/ArmIK";

        //  Topic: /arm/control/ik
        //  User's input on x, y, z axis described as a vector
        public Vector3 movement_vector { get; set; }
        // [x, y, z] values for the arm's movement in 3D space
        //  Gripper control
        //  -1: Closing
        //   0: Stopped
        //  +1: Opening
        public int gripper { get; set; }
        //  Linear Actuator movement direction
        //  -1: Retracting
        //   0: Stopped
        //  +1: Extending
        public int linear_actuator { get; set; }
        //  Laser state
        //  0: Off
        //  1: On
        public int laser { get; set; }
        //  Effector Roll movement direction
        //  -1: Counterclockwise
        //   0: No movement
        //  +1: Clockwise
        public int effector_roll { get; set; }
        //  Effector Yaw movement direction
        //  -1: Counterclockwise
        //   0: No movement
        //  +1: Clockwise
        public int effector_yaw { get; set; }

        public ArmIK()
        {
            this.movement_vector = new Vector3();
            this.gripper = 0;
            this.linear_actuator = 0;
            this.laser = 0;
            this.effector_roll = 0;
            this.effector_yaw = 0;
        }

        public ArmIK(Vector3 movement_vector, int gripper, int linear_actuator, int laser, int effector_roll, int effector_yaw)
        {
            this.movement_vector = movement_vector;
            this.gripper = gripper;
            this.linear_actuator = linear_actuator;
            this.laser = laser;
            this.effector_roll = effector_roll;
            this.effector_yaw = effector_yaw;
        }
    }
}
