/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class ArmManual : Message
    {
        public const string RosMessageName = "astra_msgs/msg/ArmManual";

        //  Topic: /arm/control/manual
        //  Axis control for rotation and speed multiplier
        //  Direction of rotation:
        //  -1: Counterclockwise
        //   0: No movement
        //  +1: Clockwise
        //  Speed multiplier:
        //  -2: 2x speed CCW
        //   0: No movement
        //  +2: 2x speed CW
        public int axis0 { get; set; }
        // Axis 0 control
        public int axis1 { get; set; }
        // Axis 1 control
        public int axis2 { get; set; }
        // Axis 2 control
        public int axis3 { get; set; }
        // Axis 3 control
        public bool brake { get; set; }
        // Whether or not to have brake mode on for arm axese
        //  Effector Roll movement direction
        //  -1: Counterclockwise
        //   0: No movement
        //  +1: Clockwise
        public int effector_roll { get; set; }
        //  Effector Yaw movement direction
        //  -1: Counterclockwise
        //   0: No movement
        //  +1: Clockwise
        public int effector_yaw { get; set; }
        //  Gripper/Drill Control
        //  -1: Closing Gripper / CCW Drilling
        //   0: Stopped
        //  +1: Opening Gripper / CW Drilling
        public int gripper { get; set; }
        //  Linear Actuator movement direction
        //  -1: Retracting
        //   0: Stopped
        //  +1: Extending
        public int linear_actuator { get; set; }
        //  Laser state
        //  0: Off
        //  1: On
        public int laser { get; set; }

        public ArmManual()
        {
            this.axis0 = 0;
            this.axis1 = 0;
            this.axis2 = 0;
            this.axis3 = 0;
            this.brake = false;
            this.effector_roll = 0;
            this.effector_yaw = 0;
            this.gripper = 0;
            this.linear_actuator = 0;
            this.laser = 0;
        }

        public ArmManual(int axis0, int axis1, int axis2, int axis3, bool brake, int effector_roll, int effector_yaw, int gripper, int linear_actuator, int laser)
        {
            this.axis0 = axis0;
            this.axis1 = axis1;
            this.axis2 = axis2;
            this.axis3 = axis3;
            this.brake = brake;
            this.effector_roll = effector_roll;
            this.effector_yaw = effector_yaw;
            this.gripper = gripper;
            this.linear_actuator = linear_actuator;
            this.laser = laser;
        }
    }
}
