/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class AutoFeedback : Message
    {
        public const string RosMessageName = "astra_msgs/msg/AutoFeedback";

        //  Current mission type
        public int mission_type { get; set; }
        //  Target Latitude
        public double target_lat { get; set; }
        //  Target Longitude
        public double target_long { get; set; }
        //  Estimated Distance remaining
        public float distance { get; set; }
        //  Update
        public string update { get; set; }
        //  Current job
        public string current { get; set; }
        //  Warning
        public string warn { get; set; }

        public AutoFeedback()
        {
            this.mission_type = 0;
            this.target_lat = 0.0;
            this.target_long = 0.0;
            this.distance = 0.0f;
            this.update = "";
            this.current = "";
            this.warn = "";
        }

        public AutoFeedback(int mission_type, double target_lat, double target_long, float distance, string update, string current, string warn)
        {
            this.mission_type = mission_type;
            this.target_lat = target_lat;
            this.target_long = target_long;
            this.distance = distance;
            this.update = update;
            this.current = current;
            this.warn = warn;
        }
    }
}
