/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class Barometer : Message
    {
        public const string RosMessageName = "astra_msgs/msg/Barometer";

        //  Holds sensor readings for a barometer-type sensor, like the BMP-388 or SHT-30.
        public Header header { get; set; }
        public double temperature { get; set; }
        // Celsius
        public double altitude { get; set; }
        // Meters
        public double pressure { get; set; }
        // mBar
        public double humidity { get; set; }
        // Percentage

        public Barometer()
        {
            this.header = new Header();
            this.temperature = 0.0;
            this.altitude = 0.0;
            this.pressure = 0.0;
            this.humidity = 0.0;
        }

        public Barometer(Header header, double temperature, double altitude, double pressure, double humidity)
        {
            this.header = header;
            this.temperature = temperature;
            this.altitude = altitude;
            this.pressure = pressure;
            this.humidity = humidity;
        }
    }
}
