/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class BioDistributor : Message
    {
        public const string RosMessageName = "astra_msgs/msg/BioDistributor";

        //  Topic: /bio/control/distributor
        public bool[] distributor_id { get; set; }
        // (0-2)

        public BioDistributor()
        {
            this.distributor_id = new bool[3];
        }

        public BioDistributor(bool[] distributor_id)
        {
            this.distributor_id = distributor_id;
        }
    }
}
