/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class BioDistributors : Message
    {
        public const string RosMessageName = "astra_msgs/msg/BioDistributors";

        //  Topic: /bio/control/distributor
        public bool distibutor_0 { get; set; }
        public bool distibutor_1 { get; set; }
        public bool distibutor_2 { get; set; }

        public BioDistributors()
        {
            this.distibutor_0 = false;
            this.distibutor_1 = false;
            this.distibutor_2 = false;
        }

        public BioDistributors(bool distibutor_0, bool distibutor_1, bool distibutor_2)
        {
            this.distibutor_0 = distibutor_0;
            this.distibutor_1 = distibutor_1;
            this.distibutor_2 = distibutor_2;
        }
    }
}
