/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class BioLaser : Message
    {
        public const string RosMessageName = "astra_msgs/msg/BioLaser";

        //  Topic /bio/control/laser
        public bool failsafe { get; set; }
        public bool fire { get; set; }

        public BioLaser()
        {
            this.failsafe = false;
            this.fire = false;
        }

        public BioLaser(bool failsafe, bool fire)
        {
            this.failsafe = failsafe;
            this.fire = fire;
        }
    }
}
