/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class CitadelControl : Message
    {
        public const string RosMessageName = "astra_msgs/msg/CitadelControl";

        //  Topic: /bio/control/citadel
        public bool[] distributor_id { get; set; }
        // (0-2)
        public float move_scythe { get; set; }
        // -1 <-> 1; Negative for up, positive for down
        public bool vibration_motor { get; set; }

        public CitadelControl()
        {
            this.distributor_id = new bool[3];
            this.move_scythe = 0.0f;
            this.vibration_motor = false;
        }

        public CitadelControl(bool[] distributor_id, float move_scythe, bool vibration_motor)
        {
            this.distributor_id = distributor_id;
            this.move_scythe = move_scythe;
            this.vibration_motor = vibration_motor;
        }
    }
}
