/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class ControllerState : Message
    {
        public const string RosMessageName = "astra_msgs/msg/ControllerState";

        //  Controller state message to transmit the entire state of the controller
        //  This is depricated and currently no longer in use. It remains as a backup in case it's needed.
        // Triggers
        public double lt { get; set; }
        public double rt { get; set; }
        // Bumbers
        public bool lb { get; set; }
        public bool rb { get; set; }
        // Menu/Pause buttons (plus/minus on the Gulikit)
        public bool plus { get; set; }
        public bool minus { get; set; }
        // Left stick values
        public double ls_x { get; set; }
        public double ls_y { get; set; }
        // Right stick values
        public double rs_x { get; set; }
        public double rs_y { get; set; }
        // Buttons
        public bool a { get; set; }
        public bool b { get; set; }
        public bool x { get; set; }
        public bool y { get; set; }
        // D-pad
        public bool d_up { get; set; }
        public bool d_down { get; set; }
        public bool d_left { get; set; }
        public bool d_right { get; set; }
        // Home button
        public bool home { get; set; }

        public ControllerState()
        {
            this.lt = 0.0;
            this.rt = 0.0;
            this.lb = false;
            this.rb = false;
            this.plus = false;
            this.minus = false;
            this.ls_x = 0.0;
            this.ls_y = 0.0;
            this.rs_x = 0.0;
            this.rs_y = 0.0;
            this.a = false;
            this.b = false;
            this.x = false;
            this.y = false;
            this.d_up = false;
            this.d_down = false;
            this.d_left = false;
            this.d_right = false;
            this.home = false;
        }

        public ControllerState(double lt, double rt, bool lb, bool rb, bool plus, bool minus, double ls_x, double ls_y, double rs_x, double rs_y, bool a, bool b, bool x, bool y, bool d_up, bool d_down, bool d_left, bool d_right, bool home)
        {
            this.lt = lt;
            this.rt = rt;
            this.lb = lb;
            this.rb = rb;
            this.plus = plus;
            this.minus = minus;
            this.ls_x = ls_x;
            this.ls_y = ls_y;
            this.rs_x = rs_x;
            this.rs_y = rs_y;
            this.a = a;
            this.b = b;
            this.x = x;
            this.y = y;
            this.d_up = d_up;
            this.d_down = d_down;
            this.d_left = d_left;
            this.d_right = d_right;
            this.home = home;
        }
    }
}
