/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class CoreFeedback : Message
    {
        public const string RosMessageName = "astra_msgs/msg/CoreFeedback";

        //  Topic: /core/feedback
        //  GPS Data
        public double gps_lat { get; set; }
        // GPS latitude
        public double gps_long { get; set; }
        // GPS longitude
        public int gps_sats { get; set; }
        // Number of active GPS satellites
        public double gps_alt { get; set; }
        // GPS altitude (m)
        //  BNO055 Sensor Data
        public Vector3 bno_gyro { get; set; }
        // x, y, z gyroscope readings from BNO055
        public Vector3 bno_accel { get; set; }
        // x, y, z acceleration readings from BNO055
        //  Rover Orientation
        public double orientation { get; set; }
        // Orientation of the rover relative to North (0 - 359 degrees)
        public int imu_calib { get; set; }
        // BNO IMU calibration status (0 - not calibrated, 13 - fully calibrated)
        //  BMP Sensor Data
        public double bmp_temp { get; set; }
        // Temperature reading in Celsius
        public double bmp_alt { get; set; }
        // Altitude reading in meters
        public double bmp_pres { get; set; }
        // Pressure reading in millibars (might be hPa)
        //  Voltage Readings
        public double bat_voltage { get; set; }
        // Current voltage of the battery
        public double voltage_12 { get; set; }
        // Current voltage of the 12V rail
        public double voltage_5 { get; set; }
        // Current voltage of the 5V rail
        public double voltage_3 { get; set; }
        // Current voltage of the 3.3V rail
        //  REV motor feedback
        //  Front left (1)
        public float fl_temp { get; set; }
        // Current motor temperature in Celsius
        public float fl_voltage { get; set; }
        // Current motor voltage in volts
        public float fl_current { get; set; }
        // Current motor amperage in milliamps
        //  Back left (2)
        public float bl_temp { get; set; }
        // Current motor temperature in Celsius
        public float bl_voltage { get; set; }
        // Current motor voltage in volts
        public float bl_current { get; set; }
        // Current motor amperage in milliamps
        //  Front right (3)
        public float fr_temp { get; set; }
        // Current motor temperature in Celsius
        public float fr_voltage { get; set; }
        // Current motor voltage in volts
        public float fr_current { get; set; }
        // Current motor amperage in milliamps
        //  Back right (4)
        public float br_temp { get; set; }
        // Current motor temperature in Celsius
        public float br_voltage { get; set; }
        // Current motor voltage in volts
        public float br_current { get; set; }
        // Current motor amperage in milliamps

        public CoreFeedback()
        {
            this.gps_lat = 0.0;
            this.gps_long = 0.0;
            this.gps_sats = 0;
            this.gps_alt = 0.0;
            this.bno_gyro = new Vector3();
            this.bno_accel = new Vector3();
            this.orientation = 0.0;
            this.imu_calib = 0;
            this.bmp_temp = 0.0;
            this.bmp_alt = 0.0;
            this.bmp_pres = 0.0;
            this.bat_voltage = 0.0;
            this.voltage_12 = 0.0;
            this.voltage_5 = 0.0;
            this.voltage_3 = 0.0;
            this.fl_temp = 0.0f;
            this.fl_voltage = 0.0f;
            this.fl_current = 0.0f;
            this.bl_temp = 0.0f;
            this.bl_voltage = 0.0f;
            this.bl_current = 0.0f;
            this.fr_temp = 0.0f;
            this.fr_voltage = 0.0f;
            this.fr_current = 0.0f;
            this.br_temp = 0.0f;
            this.br_voltage = 0.0f;
            this.br_current = 0.0f;
        }

        public CoreFeedback(double gps_lat, double gps_long, int gps_sats, double gps_alt, Vector3 bno_gyro, Vector3 bno_accel, double orientation, int imu_calib, double bmp_temp, double bmp_alt, double bmp_pres, double bat_voltage, double voltage_12, double voltage_5, double voltage_3, float fl_temp, float fl_voltage, float fl_current, float bl_temp, float bl_voltage, float bl_current, float fr_temp, float fr_voltage, float fr_current, float br_temp, float br_voltage, float br_current)
        {
            this.gps_lat = gps_lat;
            this.gps_long = gps_long;
            this.gps_sats = gps_sats;
            this.gps_alt = gps_alt;
            this.bno_gyro = bno_gyro;
            this.bno_accel = bno_accel;
            this.orientation = orientation;
            this.imu_calib = imu_calib;
            this.bmp_temp = bmp_temp;
            this.bmp_alt = bmp_alt;
            this.bmp_pres = bmp_pres;
            this.bat_voltage = bat_voltage;
            this.voltage_12 = voltage_12;
            this.voltage_5 = voltage_5;
            this.voltage_3 = voltage_3;
            this.fl_temp = fl_temp;
            this.fl_voltage = fl_voltage;
            this.fl_current = fl_current;
            this.bl_temp = bl_temp;
            this.bl_voltage = bl_voltage;
            this.bl_current = bl_current;
            this.fr_temp = fr_temp;
            this.fr_voltage = fr_voltage;
            this.fr_current = fr_current;
            this.br_temp = br_temp;
            this.br_voltage = br_voltage;
            this.br_current = br_current;
        }
    }
}
