/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class CoreCtrlState : Message
    {
        public const string RosMessageName = "astra_msgs/msg/CoreCtrlState";

        //  /core/control/state
        public bool brake_mode { get; set; }
        // True = brake, False = coast
        public float max_duty { get; set; }
        // Max duty cycle setting (0.0 - 1.0); walking speed is 0.5

        public CoreCtrlState()
        {
            this.brake_mode = false;
            this.max_duty = 0.0f;
        }

        public CoreCtrlState(bool brake_mode, float max_duty)
        {
            this.brake_mode = brake_mode;
            this.max_duty = max_duty;
        }
    }
}
