/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class CoreControl : Message
    {
        public const string RosMessageName = "astra_msgs/msg/CoreControl";

        //  Topic: /core/control
        //  Left and right stick control
        //  Percentage of max speed for each stick (range: 0.0 to 1.0)
        public float left_stick { get; set; }
        // Left stick percentage of max speed
        public float right_stick { get; set; }
        // Right stick percentage of max speed
        //  Maximum speed setting
        public int max_speed { get; set; }
        // Maximum duty cycle (range: 0 to 100)
        //  Brake mode
        public bool brake { get; set; }
        // Is brake mode enabled?
        //  Enable autonomy turning
        public bool turn_to_enable { get; set; }
        // Use turning to and ignore other control commands
        //  Turn to absolute angle
        public float turn_to { get; set; }
        // Absolute angle, in degrees, to turn to
        //  Turn to timeout
        public float turn_to_timeout { get; set; }
        // Time for turnto to timeout (seconds)

        public CoreControl()
        {
            this.left_stick = 0.0f;
            this.right_stick = 0.0f;
            this.max_speed = 0;
            this.brake = false;
            this.turn_to_enable = false;
            this.turn_to = 0.0f;
            this.turn_to_timeout = 0.0f;
        }

        public CoreControl(float left_stick, float right_stick, int max_speed, bool brake, bool turn_to_enable, float turn_to, float turn_to_timeout)
        {
            this.left_stick = left_stick;
            this.right_stick = right_stick;
            this.max_speed = max_speed;
            this.brake = brake;
            this.turn_to_enable = turn_to_enable;
            this.turn_to = turn_to;
            this.turn_to_timeout = turn_to_timeout;
        }
    }
}
