/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class FaerieControl : Message
    {
        public const string RosMessageName = "astra_msgs/msg/FaerieControl";

        //  Topic: /bio/control/faerie
        public float move_faerie { get; set; }
        // Negative for up, positive for down
        public float drill_speed { get; set; }
        // -1 <-> 1
        public bool vibration_motor { get; set; }

        public FaerieControl()
        {
            this.move_faerie = 0.0f;
            this.drill_speed = 0.0f;
            this.vibration_motor = false;
        }

        public FaerieControl(float move_faerie, float drill_speed, bool vibration_motor)
        {
            this.move_faerie = move_faerie;
            this.drill_speed = drill_speed;
            this.vibration_motor = vibration_motor;
        }
    }
}
