/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class MaculaFeedback : Message
    {
        public const string RosMessageName = "astra_msgs/msg/MaculaFeedback";

        //  Topic: /auto/macula
        //  Flag for ArUco/Objected detected
        public bool detected { get; set; }
        //  Id of detected ArUco tag, 51 for Object
        public int object_id { get; set; }
        //  Corners of object
        public float x0 { get; set; }
        public float y0 { get; set; }
        public float x1 { get; set; }
        public float y1 { get; set; }
        public float x2 { get; set; }
        public float y2 { get; set; }
        public float x3 { get; set; }
        public float y3 { get; set; }

        public MaculaFeedback()
        {
            this.detected = false;
            this.object_id = 0;
            this.x0 = 0.0f;
            this.y0 = 0.0f;
            this.x1 = 0.0f;
            this.y1 = 0.0f;
            this.x2 = 0.0f;
            this.y2 = 0.0f;
            this.x3 = 0.0f;
            this.y3 = 0.0f;
        }

        public MaculaFeedback(bool detected, int object_id, float x0, float y0, float x1, float y1, float x2, float y2, float x3, float y3)
        {
            this.detected = detected;
            this.object_id = object_id;
            this.x0 = x0;
            this.y0 = y0;
            this.x1 = x1;
            this.y1 = y1;
            this.x2 = x2;
            this.y2 = y2;
            this.x3 = x3;
            this.y3 = y3;
        }
    }
}
