/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Astra;

namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class NewBioFeedback : Message
    {
        public const string RosMessageName = "astra_msgs/msg/NewBioFeedback";

        //  Topic: /bio/new_feedback
        //  PCB Voltage Readings
        public BoardVoltage board_voltage { get; set; }
        //  SHT sensor data
        public float drill_temp { get; set; }
        // Temperature in Celsius from the SHT on the drill
        public float drill_humidity { get; set; }
        // Humidity in percentage from the SHT on the drill
        public bool ground_contact { get; set; }
        // If the end of lance is currently pressed in

        public NewBioFeedback()
        {
            this.board_voltage = new BoardVoltage();
            this.drill_temp = 0.0f;
            this.drill_humidity = 0.0f;
            this.ground_contact = false;
        }

        public NewBioFeedback(BoardVoltage board_voltage, float drill_temp, float drill_humidity, bool ground_contact)
        {
            this.board_voltage = board_voltage;
            this.drill_temp = drill_temp;
            this.drill_humidity = drill_humidity;
            this.ground_contact = ground_contact;
        }
    }
}
