/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class PtzFeedback : Message
    {
        public const string RosMessageName = "astra_msgs/msg/PtzFeedback";

        //  Topic: /ptz/feedback
        //  Camera attitude
        public float yaw { get; set; }
        // Current yaw angle in degrees
        public float pitch { get; set; }
        // Current pitch angle in degrees
        public float roll { get; set; }
        // Current roll angle in degrees
        //  Angular velocities (raw values from camera)
        public int yaw_velocity { get; set; }
        public int pitch_velocity { get; set; }
        public int roll_velocity { get; set; }
        //  Connection status
        public bool connected { get; set; }
        // True if connected to camera
        //  Error information
        public string error_msg { get; set; }
        // Empty if no error

        public PtzFeedback()
        {
            this.yaw = 0.0f;
            this.pitch = 0.0f;
            this.roll = 0.0f;
            this.yaw_velocity = 0;
            this.pitch_velocity = 0;
            this.roll_velocity = 0;
            this.connected = false;
            this.error_msg = "";
        }

        public PtzFeedback(float yaw, float pitch, float roll, int yaw_velocity, int pitch_velocity, int roll_velocity, bool connected, string error_msg)
        {
            this.yaw = yaw;
            this.pitch = pitch;
            this.roll = roll;
            this.yaw_velocity = yaw_velocity;
            this.pitch_velocity = pitch_velocity;
            this.roll_velocity = roll_velocity;
            this.connected = connected;
            this.error_msg = error_msg;
        }
    }
}
