/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class RevMotorState : Message
    {
        public const string RosMessageName = "astra_msgs/msg/RevMotorState";

        //  This message holds all relevant state data for a REV NEO-550 or Brushless V1.1,
        //  communicated over CAN bus using the REV CAN SPARK MAX motor controller.
        //  All information is from the perspective of the motor (except for maybe the temperature?)
        //  Scaling is needed for JointState publishing.
        public Header header { get; set; }
        public int id { get; set; }
        // REV motor ID (1-63)
        public float position { get; set; }
        // Rotations
        public float velocity { get; set; }
        // RPM
        public float voltage { get; set; }
        // Volts
        public float current { get; set; }
        // Amps
        public float temperature { get; set; }
        // Celsius

        public RevMotorState()
        {
            this.header = new Header();
            this.id = 0;
            this.position = 0.0f;
            this.velocity = 0.0f;
            this.voltage = 0.0f;
            this.current = 0.0f;
            this.temperature = 0.0f;
        }

        public RevMotorState(Header header, int id, float position, float velocity, float voltage, float current, float temperature)
        {
            this.header = header;
            this.id = id;
            this.position = position;
            this.velocity = velocity;
            this.voltage = voltage;
            this.current = current;
            this.temperature = temperature;
        }
    }
}
