/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class ScytheControl : Message
    {
        public const string RosMessageName = "astra_msgs/msg/ScytheControl";

        //  Topic: /bio/control/scythe
        public float move_scythe { get; set; }
        // -1 <-> 1; Negative for up, positive for down

        public ScytheControl()
        {
            this.move_scythe = 0.0f;
        }

        public ScytheControl(float move_scythe)
        {
            this.move_scythe = move_scythe;
        }
    }
}
