/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class VicCAN : Message
    {
        public const string RosMessageName = "astra_msgs/msg/VicCAN";

        public Header header { get; set; }
        //  https://docs.google.com/spreadsheets/d/1-Tdnsv2_-r8CBJNxPaAmIR2wMPSTix63AkemrWzVJVY/edit?gid=586685598#gid=586685598
        public string mcu_name { get; set; }
        public uint command_id { get; set; }
        public double[] data { get; set; }

        public VicCAN()
        {
            this.header = new Header();
            this.mcu_name = "";
            this.command_id = 0;
            this.data = new double[8];
        }

        public VicCAN(Header header, string mcu_name, uint command_id, double[] data)
        {
            this.header = header;
            this.mcu_name = mcu_name;
            this.command_id = command_id;
            this.data = data;
        }
    }
}
