/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class BioCCDResponse : Message
    {
        public const string RosMessageName = "astra_msgs/srv/BioCCD";

        //  Result
        public float[] ccd_data { get; set; }

        public BioCCDResponse()
        {
            this.ccd_data = new float[3648];
        }

        public BioCCDResponse(float[] ccd_data)
        {
            this.ccd_data = ccd_data;
        }
    }
}
