/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class BioCCDRequest : Message
    {
        public const string RosMessageName = "astra_msgs/srv/BioCCD";

        //  Topic: /bio/feedback/CCD
        //  Goal
        public bool request { get; set; }
        // Request CCD image

        public BioCCDRequest()
        {
            this.request = false;
        }

        public BioCCDRequest(bool request)
        {
            this.request = request;
        }
    }
}
