/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class BioTestTubeRequest : Message
    {
        public const string RosMessageName = "astra_msgs/srv/BioTestTube";

        //  Topic: /bio/control/test_tube
        //  Goal
        public sbyte tube_id { get; set; }
        public sbyte extension_percent { get; set; }

        public BioTestTubeRequest()
        {
            this.tube_id = 0;
            this.extension_percent = 0;
        }

        public BioTestTubeRequest(sbyte tube_id, sbyte extension_percent)
        {
            this.tube_id = tube_id;
            this.extension_percent = extension_percent;
        }
    }
}
