/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class BioTestTubesRequest : Message
    {
        public const string RosMessageName = "astra_msgs/srv/BioTestTubes";

        //  Topic: /bio/control/testtubes
        //  Goal
        public sbyte tube_id { get; set; }

        public BioTestTubesRequest()
        {
            this.tube_id = 0;
        }

        public BioTestTubesRequest(sbyte tube_id)
        {
            this.tube_id = tube_id;
        }
    }
}
