/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class FireLibsRequest : Message
    {
        public const string RosMessageName = "astra_msgs/srv/FireLibs";

        //  Topic: /bio/libs/fire
        //  Goal
        public long unique_number { get; set; }
        // Pass a unique number (per anchor restart) to allow LIBS to fire

        public FireLibsRequest()
        {
            this.unique_number = 0;
        }

        public FireLibsRequest(long unique_number)
        {
            this.unique_number = unique_number;
        }
    }
}
