/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class LibsSystemRequest : Message
    {
        public const string RosMessageName = "astra_msgs/srv/LibsSystem";

        //  Topic: /bio/control/libs_system
        //  Goal
        public bool fire_laser { get; set; }
        // Request CCD image

        public LibsSystemRequest()
        {
            this.fire_laser = false;
        }

        public LibsSystemRequest(bool fire_laser)
        {
            this.fire_laser = fire_laser;
        }
    }
}
