/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class DynamicInterfaceGroupValues : Message
    {
        public const string RosMessageName = "control_msgs/msg/DynamicInterfaceGroupValues";

        public Header header { get; set; }
        //  List of interface group names , e.g. ["flange_analog_IOs", "flange_vacuum"]
        public string[] interface_groups { get; set; }
        //  Key-value pairs representing interfaces and their corresponding values for each interface group listed in `interface_groups`
        public InterfaceValue[] interface_values { get; set; }

        public DynamicInterfaceGroupValues()
        {
            this.header = new Header();
            this.interface_groups = new string[0];
            this.interface_values = new InterfaceValue[0];
        }

        public DynamicInterfaceGroupValues(Header header, string[] interface_groups, InterfaceValue[] interface_values)
        {
            this.header = header;
            this.interface_groups = interface_groups;
            this.interface_values = interface_values;
        }
    }
}
