/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class MecanumDriveControllerState : Message
    {
        public const string RosMessageName = "control_msgs/msg/MecanumDriveControllerState";

        public Header header { get; set; }
        public double front_left_wheel_velocity { get; set; }
        public double back_left_wheel_velocity { get; set; }
        public double back_right_wheel_velocity { get; set; }
        public double front_right_wheel_velocity { get; set; }
        public Twist reference_velocity { get; set; }

        public MecanumDriveControllerState()
        {
            this.header = new Header();
            this.front_left_wheel_velocity = 0.0;
            this.back_left_wheel_velocity = 0.0;
            this.back_right_wheel_velocity = 0.0;
            this.front_right_wheel_velocity = 0.0;
            this.reference_velocity = new Twist();
        }

        public MecanumDriveControllerState(Header header, double front_left_wheel_velocity, double back_left_wheel_velocity, double back_right_wheel_velocity, double front_right_wheel_velocity, Twist reference_velocity)
        {
            this.header = header;
            this.front_left_wheel_velocity = front_left_wheel_velocity;
            this.back_left_wheel_velocity = back_left_wheel_velocity;
            this.back_right_wheel_velocity = back_right_wheel_velocity;
            this.front_right_wheel_velocity = front_right_wheel_velocity;
            this.reference_velocity = reference_velocity;
        }
    }
}
