/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class MultiDOFStateStamped : Message
    {
        public const string RosMessageName = "control_msgs/msg/MultiDOFStateStamped";

        //  This message presents current controller state of multiple degrees of freedom.
        //  Header timestamp should be update time of controller state
        public Header header { get; set; }
        public SingleDOFState[] dof_states { get; set; }

        public MultiDOFStateStamped()
        {
            this.header = new Header();
            this.dof_states = new SingleDOFState[0];
        }

        public MultiDOFStateStamped(Header header, SingleDOFState[] dof_states)
        {
            this.header = header;
            this.dof_states = dof_states;
        }
    }
}
