/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class SingleDOFState : Message
    {
        public const string RosMessageName = "control_msgs/msg/SingleDOFState";

        //  This message presents current controller state of one degree of freedom.
        //  DoF name, e.g., joint or Cartesian axis name
        public string name { get; set; }
        //  The set point, that is, desired state.
        public double reference { get; set; }
        //  Current value of the process (ie: latest sensor measurement on the controlled value).
        public double feedback { get; set; }
        //  First time-derivative of the process value. E.g., velocity.
        public double feedback_dot { get; set; }
        //  The error of the controlled value, essentially process_value - set_point (for a regular PID implementation).
        public double error { get; set; }
        //  First time-derivative of the error of the controlled value.
        public double error_dot { get; set; }
        //  Time between two consecutive updates/execution of the control law.
        public double time_step { get; set; }
        //  Current output of the controller.
        public double output { get; set; }

        public SingleDOFState()
        {
            this.name = "";
            this.reference = 0.0;
            this.feedback = 0.0;
            this.feedback_dot = 0.0;
            this.error = 0.0;
            this.error_dot = 0.0;
            this.time_step = 0.0;
            this.output = 0.0;
        }

        public SingleDOFState(string name, double reference, double feedback, double feedback_dot, double error, double error_dot, double time_step, double output)
        {
            this.name = name;
            this.reference = reference;
            this.feedback = feedback;
            this.feedback_dot = feedback_dot;
            this.error = error;
            this.error_dot = error_dot;
            this.time_step = time_step;
            this.output = output;
        }
    }
}
