/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class SteeringControllerStatus : Message
    {
        public const string RosMessageName = "control_msgs/msg/SteeringControllerStatus";

        public Header header { get; set; }
        public double[] traction_wheels_position { get; set; }
        // positions of traction wheels if the robot is controlled by position
        public double[] traction_wheels_velocity { get; set; }
        // velocities of traction wheels if the robot is controlled by velocity
        public double[] steer_positions { get; set; }
        // positions of steering joints
        public double[] linear_velocity_command { get; set; }
        // value commanded to tractions joint
        public double[] steering_angle_command { get; set; }
        // values commanded to steering joints

        public SteeringControllerStatus()
        {
            this.header = new Header();
            this.traction_wheels_position = new double[0];
            this.traction_wheels_velocity = new double[0];
            this.steer_positions = new double[0];
            this.linear_velocity_command = new double[0];
            this.steering_angle_command = new double[0];
        }

        public SteeringControllerStatus(Header header, double[] traction_wheels_position, double[] traction_wheels_velocity, double[] steer_positions, double[] linear_velocity_command, double[] steering_angle_command)
        {
            this.header = header;
            this.traction_wheels_position = traction_wheels_position;
            this.traction_wheels_velocity = traction_wheels_velocity;
            this.steer_positions = steer_positions;
            this.linear_velocity_command = linear_velocity_command;
            this.steering_angle_command = steering_angle_command;
        }
    }
}
