/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class AutoNav : Message
    {
        public const string RosMessageName = "astra_msgs/msg/AutoNav";

        //  topic /auto/nav
        //  Flag to enable/disable Nav2
        public bool enable { get; set; }
        //  Targets
        public double lat_target { get; set; }
        public double long_target { get; set; }
        //  Emergency "Nav 2 is failing" flag
        public bool fail { get; set; }

        public AutoNav()
        {
            this.enable = false;
            this.lat_target = 0.0;
            this.long_target = 0.0;
            this.fail = false;
        }

        public AutoNav(bool enable, double lat_target, double long_target, bool fail)
        {
            this.enable = enable;
            this.lat_target = lat_target;
            this.long_target = long_target;
            this.fail = fail;
        }
    }
}
