/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class BioControl : Message
    {
        public const string RosMessageName = "astra_msgs/msg/BioControl";

        //  Topic: /bio/control
        // # CITADEL
        //  Pumps: [0] = which one (1-4), [1] = how much fluid (mL)
        //  VicCAN: 27 - Stepper motor
        public int pump_id { get; set; }
        public double pump_amount { get; set; }
        //  Fans: [0] = which one (1-3), [1] = duration (ms)
        //  VicCAN: 40 - CITADEL fan
        public int fan_id { get; set; }
        public int fan_duration { get; set; }
        //  PWM servos: which one (1-3), wiggle state (true or false)
        //  VicCAN: 25 - PWM servo
        public int servo_id { get; set; }
        public bool servo_state { get; set; }
        //  Bio arm (Scythe): -100 thru 100 for direction and speed. Positive is up and negative is down.
        //  VicCAN: 24 - LSS
        public int bio_arm { get; set; }
        //  Vibration motor: [0] = on/off (1/0)
        //  VicCAN: 26 - DC motor
        public int vibration_motor { get; set; }
        // # FAERIE
        //  Laser: [0] = on/off (0 or 1)
        //  VicCAN: 28 - Laser
        public int laser { get; set; }
        //  Drill: -100 thru 100 for direction and speed. Positive is CW and negative is CCW.
        //  VicCAN: 19 - REV motor duty cycle
        public int drill { get; set; }
        //  Linear Actuator: same deal as bio arm
        //  VicCAN: 42 - FAERIE bio arm
        public int drill_arm { get; set; }

        public BioControl()
        {
            this.pump_id = 0;
            this.pump_amount = 0.0;
            this.fan_id = 0;
            this.fan_duration = 0;
            this.servo_id = 0;
            this.servo_state = false;
            this.bio_arm = 0;
            this.vibration_motor = 0;
            this.laser = 0;
            this.drill = 0;
            this.drill_arm = 0;
        }

        public BioControl(int pump_id, double pump_amount, int fan_id, int fan_duration, int servo_id, bool servo_state, int bio_arm, int vibration_motor, int laser, int drill, int drill_arm)
        {
            this.pump_id = pump_id;
            this.pump_amount = pump_amount;
            this.fan_id = fan_id;
            this.fan_duration = fan_duration;
            this.servo_id = servo_id;
            this.servo_state = servo_state;
            this.bio_arm = bio_arm;
            this.vibration_motor = vibration_motor;
            this.laser = laser;
            this.drill = drill;
            this.drill_arm = drill_arm;
        }
    }
}
