/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class BioFeedback : Message
    {
        public const string RosMessageName = "astra_msgs/msg/BioFeedback";

        //  Topic: /arm/feedback/bio
        //  Voltage readings
        public float bat_voltage { get; set; }
        // Current voltage of the battery
        public float voltage_12 { get; set; }
        // Current voltage of the 12V rail
        public float voltage_5 { get; set; }
        // Current voltage of the 5V rail
        //  SHT sensor data
        public float drill_temp { get; set; }
        // Temperature in Celsius from the SHT on the drill
        public float drill_humidity { get; set; }
        // Humidity in percentage from the SHT on the drill

        public BioFeedback()
        {
            this.bat_voltage = 0.0f;
            this.voltage_12 = 0.0f;
            this.voltage_5 = 0.0f;
            this.drill_temp = 0.0f;
            this.drill_humidity = 0.0f;
        }

        public BioFeedback(float bat_voltage, float voltage_12, float voltage_5, float drill_temp, float drill_humidity)
        {
            this.bat_voltage = bat_voltage;
            this.voltage_12 = voltage_12;
            this.voltage_5 = voltage_5;
            this.drill_temp = drill_temp;
            this.drill_humidity = drill_humidity;
        }
    }
}
