/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class BoardVoltage : Message
    {
        public const string RosMessageName = "astra_msgs/msg/BoardVoltage";

        //  Holds voltage divider readings for a particular PCB. Set a value to 0 if not read.
        public Header header { get; set; }
        public float vbatt { get; set; }
        public float v12 { get; set; }
        public float v5 { get; set; }
        public float v3 { get; set; }

        public BoardVoltage()
        {
            this.header = new Header();
            this.vbatt = 0.0f;
            this.v12 = 0.0f;
            this.v5 = 0.0f;
            this.v3 = 0.0f;
        }

        public BoardVoltage(Header header, float vbatt, float v12, float v5, float v3)
        {
            this.header = header;
            this.vbatt = vbatt;
            this.v12 = v12;
            this.v5 = v5;
            this.v3 = v3;
        }
    }
}
