/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class DigitFeedback : Message
    {
        public const string RosMessageName = "astra_msgs/msg/DigitFeedback";

        //  Topic: /arm/feedback/digit
        //  Current wrist yaw angle
        public float wrist_angle { get; set; }
        //  Current voltage of the battery
        public float bat_voltage { get; set; }
        //  Current voltage of the 12V rail
        public float voltage_12 { get; set; }
        //  Current voltage of the 5V rail
        public float voltage_5 { get; set; }

        public DigitFeedback()
        {
            this.wrist_angle = 0.0f;
            this.bat_voltage = 0.0f;
            this.voltage_12 = 0.0f;
            this.voltage_5 = 0.0f;
        }

        public DigitFeedback(float wrist_angle, float bat_voltage, float voltage_12, float voltage_5)
        {
            this.wrist_angle = wrist_angle;
            this.bat_voltage = bat_voltage;
            this.voltage_12 = voltage_12;
            this.voltage_5 = voltage_5;
        }
    }
}
