/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Astra;

namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class NewCoreFeedback : Message
    {
        public const string RosMessageName = "astra_msgs/msg/NewCoreFeedback";

        //  Replaces old CoreFeedback. Consolidates motor and voltage readings, and moves IMU and GPS readings to their own topics.
        public Header header { get; set; }
        public float orientation { get; set; }
        // Heading of the rover relative to North (0 - 359 degrees)
        public int imu_calib { get; set; }
        // BNO055 IMU calibration status (0 - not calibrated, 3333 - fully calibrated)
        //  PCB Voltage Readings
        public BoardVoltage board_voltage { get; set; }
        //  REV motor feedback
        //  Front left (1)
        public RevMotorState fl_motor { get; set; }
        //  Back left (2)
        public RevMotorState bl_motor { get; set; }
        //  Front right (3)
        public RevMotorState fr_motor { get; set; }
        //  Back right (4)
        public RevMotorState br_motor { get; set; }

        public NewCoreFeedback()
        {
            this.header = new Header();
            this.orientation = 0.0f;
            this.imu_calib = 0;
            this.board_voltage = new BoardVoltage();
            this.fl_motor = new RevMotorState();
            this.bl_motor = new RevMotorState();
            this.fr_motor = new RevMotorState();
            this.br_motor = new RevMotorState();
        }

        public NewCoreFeedback(Header header, float orientation, int imu_calib, BoardVoltage board_voltage, RevMotorState fl_motor, RevMotorState bl_motor, RevMotorState fr_motor, RevMotorState br_motor)
        {
            this.header = header;
            this.orientation = orientation;
            this.imu_calib = imu_calib;
            this.board_voltage = board_voltage;
            this.fl_motor = fl_motor;
            this.bl_motor = bl_motor;
            this.fr_motor = fr_motor;
            this.br_motor = br_motor;
        }
    }
}
