/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class PtzControl : Message
    {
        public const string RosMessageName = "astra_msgs/msg/PtzControl";

        //  Topic: /ptz/control
        //  Control mode
        //  0: Relative speed control (using turn_yaw/turn_pitch)
        //  1: Absolute angle control (using yaw/pitch)
        //  2: Single axis control (using axis_id and angle)
        //  3: Absolute zoom control (using zoom_level)
        public int control_mode { get; set; }
        //  Relative speed control (-100 to 100)
        public int turn_yaw { get; set; }
        // Horizontal rotation speed
        public int turn_pitch { get; set; }
        // Vertical rotation speed
        //  Absolute angle control (in degrees)
        public float yaw { get; set; }
        // Horizontal angle (-135 to 135 for A8 mini)
        public float pitch { get; set; }
        // Vertical angle (-90 to 90 for A8 mini, check specific model)
        //  Single axis control
        public int axis_id { get; set; }
        // 0 for yaw, 1 for pitch
        public float angle { get; set; }
        // Angle for the specified axis (degrees)
        //  Absolute zoom control
        public float zoom_level { get; set; }
        // Target zoom level (e.g., 1.0 for 1x, 2.5 for 2.5x, up to camera max e.g. 6.0)
        //  Data streaming configuration (optional, can be set via this message)
        //  Use -1 or omit if not changing stream settings with this control command
        public int stream_type { get; set; }
        // 1: Attitude, 2: Laser range, 3: Magnetic encoder, 4: Motor voltage. (Use e.g. -1 to ignore)
        public int stream_freq { get; set; }
        // 0: Disable, 1: 2Hz, ..., 7: 100Hz. (Use e.g. -1 to ignore)
        //  Reset command (set to true to reset camera to center position and optionally 1x zoom)
        public bool reset { get; set; }

        public PtzControl()
        {
            this.control_mode = 0;
            this.turn_yaw = 0;
            this.turn_pitch = 0;
            this.yaw = 0.0f;
            this.pitch = 0.0f;
            this.axis_id = 0;
            this.angle = 0.0f;
            this.zoom_level = 0.0f;
            this.stream_type = 0;
            this.stream_freq = 0;
            this.reset = false;
        }

        public PtzControl(int control_mode, int turn_yaw, int turn_pitch, float yaw, float pitch, int axis_id, float angle, float zoom_level, int stream_type, int stream_freq, bool reset)
        {
            this.control_mode = control_mode;
            this.turn_yaw = turn_yaw;
            this.turn_pitch = turn_pitch;
            this.yaw = yaw;
            this.pitch = pitch;
            this.axis_id = axis_id;
            this.angle = angle;
            this.zoom_level = zoom_level;
            this.stream_type = stream_type;
            this.stream_freq = stream_freq;
            this.reset = reset;
        }
    }
}
