/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Astra
{
    public class SocketFeedback : Message
    {
        public const string RosMessageName = "astra_msgs/msg/SocketFeedback";

        //  Topic: /arm/feedback/socket
        //  Axis 0 feedback
        public float axis0_angle { get; set; }
        // Current joint angle in degrees
        public float axis0_temp { get; set; }
        // Current motor temperature in Celsius
        public float axis0_voltage { get; set; }
        // Current motor voltage in volts
        public float axis0_current { get; set; }
        // Current motor amperage in milliamps
        //  Axis 1 feedback
        public float axis1_angle { get; set; }
        // Current joint angle in degrees
        public float axis1_temp { get; set; }
        // Current motor temperature in Celsius
        public float axis1_voltage { get; set; }
        // Current motor voltage in volts
        public float axis1_current { get; set; }
        // Current motor amperage in milliamps
        //  Axis 2 feedback
        public float axis2_angle { get; set; }
        // Current joint angle in degrees
        public float axis2_temp { get; set; }
        // Current motor temperature in Celsius
        public float axis2_voltage { get; set; }
        // Current motor voltage in volts
        public float axis2_current { get; set; }
        // Current motor amperage in milliamps
        //  Axis 3 feedback
        public float axis3_angle { get; set; }
        // Current joint angle in degrees
        public float axis3_temp { get; set; }
        // Current motor temperature in Celsius
        public float axis3_voltage { get; set; }
        // Current motor voltage in volts
        public float axis3_current { get; set; }
        // Current motor amperage in milliamps
        //  Voltage feedback
        public float bat_voltage { get; set; }
        // Current voltage of the battery
        public float voltage_12 { get; set; }
        // Current voltage of the 12V rail
        public float voltage_5 { get; set; }
        // Current voltage of the 5V rail
        public float voltage_3 { get; set; }
        // Current voltage of the 3.3V rail

        public SocketFeedback()
        {
            this.axis0_angle = 0.0f;
            this.axis0_temp = 0.0f;
            this.axis0_voltage = 0.0f;
            this.axis0_current = 0.0f;
            this.axis1_angle = 0.0f;
            this.axis1_temp = 0.0f;
            this.axis1_voltage = 0.0f;
            this.axis1_current = 0.0f;
            this.axis2_angle = 0.0f;
            this.axis2_temp = 0.0f;
            this.axis2_voltage = 0.0f;
            this.axis2_current = 0.0f;
            this.axis3_angle = 0.0f;
            this.axis3_temp = 0.0f;
            this.axis3_voltage = 0.0f;
            this.axis3_current = 0.0f;
            this.bat_voltage = 0.0f;
            this.voltage_12 = 0.0f;
            this.voltage_5 = 0.0f;
            this.voltage_3 = 0.0f;
        }

        public SocketFeedback(float axis0_angle, float axis0_temp, float axis0_voltage, float axis0_current, float axis1_angle, float axis1_temp, float axis1_voltage, float axis1_current, float axis2_angle, float axis2_temp, float axis2_voltage, float axis2_current, float axis3_angle, float axis3_temp, float axis3_voltage, float axis3_current, float bat_voltage, float voltage_12, float voltage_5, float voltage_3)
        {
            this.axis0_angle = axis0_angle;
            this.axis0_temp = axis0_temp;
            this.axis0_voltage = axis0_voltage;
            this.axis0_current = axis0_current;
            this.axis1_angle = axis1_angle;
            this.axis1_temp = axis1_temp;
            this.axis1_voltage = axis1_voltage;
            this.axis1_current = axis1_current;
            this.axis2_angle = axis2_angle;
            this.axis2_temp = axis2_temp;
            this.axis2_voltage = axis2_voltage;
            this.axis2_current = axis2_current;
            this.axis3_angle = axis3_angle;
            this.axis3_temp = axis3_temp;
            this.axis3_voltage = axis3_voltage;
            this.axis3_current = axis3_current;
            this.bat_voltage = bat_voltage;
            this.voltage_12 = voltage_12;
            this.voltage_5 = voltage_5;
            this.voltage_3 = voltage_3;
        }
    }
}
